<script setup lang="ts">
import { onBeforeUnmount,reactive,ref } from 'vue'
import { stories } from '../data/lessonData'
const drafts=reactive(structuredClone(stories))
const selected=ref<keyof typeof stories>('concert'),form=reactive({...drafts.concert}),recording=ref(false),audio=ref(''),status=ref('尚未请求麦克风权限'),ratings=reactive({fluency:0,vocabulary:0,grammar:0,pronunciation:0});let media:MediaRecorder|undefined,stream:MediaStream|undefined,chunks:Blob[]=[];let stopTimer:number|undefined
function choose(key:keyof typeof stories){Object.assign(drafts[selected.value],form);selected.value=key;Object.assign(form,drafts[key])}
async function record(){if(recording.value){stop();return}if(!navigator.mediaDevices||!window.MediaRecorder){status.value='浏览器不支持录音，请使用计时训练。';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];media=new MediaRecorder(stream);media.ondataavailable=e=>chunks.push(e.data);media.onstop=()=>{if(audio.value)URL.revokeObjectURL(audio.value);audio.value=URL.createObjectURL(new Blob(chunks,{type:media?.mimeType}));stream?.getTracks().forEach(t=>t.stop());recording.value=false;status.value='录音完成，请回放后自评。'};media.start();recording.value=true;status.value='正在录音，最多 2 分钟…';stopTimer=window.setTimeout(stop,120000)}catch{status.value='没有麦克风权限，已切换为纯计时模式。'}}
function stop(){clearTimeout(stopTimer);if(media?.state==='recording')media.stop()}
onBeforeUnmount(()=>{stop();stream?.getTracks().forEach(t=>t.stop());if(audio.value)URL.revokeObjectURL(audio.value)})
</script>
<template><el-card class="speaking-lab" shadow="never"><template #header><b>6–6.5 安全故事库</b></template><el-tabs :model-value="selected" @tab-change="(v: string|number)=>choose(v as keyof typeof stories)"><el-tab-pane label="薛之谦演唱会" name="concert"/><el-tab-pane label="Tokyo Beauty 工作" name="work"/><el-tab-pane label="朋友婚礼" name="wedding"/><el-tab-pane label="＋ 自定义故事" name="custom"/></el-tabs><el-form label-position="top"><el-form-item label="人物"><el-input v-model="form.person" type="textarea" autosize/></el-form-item><el-form-item label="事件和地点"><el-input v-model="form.event" type="textarea" autosize/></el-form-item><el-form-item label="主要经过"><el-input v-model="form.action" type="textarea" autosize/></el-form-item><el-form-item label="补充细节"><el-input v-model="form.extra" type="textarea" autosize/></el-form-item><el-form-item label="结果和感受"><el-input v-model="form.result" type="textarea" autosize/></el-form-item></el-form><div class="generated"><p><strong>Opening · I'd like to talk about</strong> {{form.event}}. <strong>It was special to me, and I still remember it clearly.</strong></p><p><strong>Person · I was with</strong> {{form.person}}. <strong>Having them there made the experience more enjoyable.</strong></p><p><strong>Main event · What happened was that</strong> {{form.action}}.</p><p><strong>Details · To give a little more detail,</strong> {{form.extra}}.</p><p><strong>Reaction · At first, I felt a little nervous or tired, but I soon became more relaxed. I tried to enjoy the experience and pay attention to what was happening around me.</strong></p><p><strong>Result · In the end,</strong> {{form.result}}.</p><p><strong>Reflection · Overall, it was a memorable experience because it was both enjoyable and meaningful. I learned something useful from it, and I would be happy to have a similar experience again in the future.</strong></p><small>所有粗体文字都是可重复使用的固定模板；普通字重文字是每个故事需要替换的个人素材。</small></div><el-divider/><el-button :type="recording?'danger':'primary'" @click="record">{{recording?'停止录音':'开始录音'}}</el-button><span class="record-status">{{status}}</span><audio v-if="audio" :src="audio" controls/><div class="ratings"><label v-for="(_,key) in ratings" :key="key">{{key}}<el-rate v-model="ratings[key]"/></label></div><div class="self-check"><b>回听检查：</b>是否说够 1分30秒？是否有超过 3 秒沉默？过去时是否稳定？故事是否按背景→经过→结果→感受展开？是否自然使用 because / although？</div></el-card></template>
