<script setup lang="ts">
defineProps<{kind:'letter'|'essay'}>()
const letters=[
 {name:'Formal 正式信',signal:'写给不认识的个人、公司或机构，例如酒店经理、航空公司、培训中心。',greeting:'Dear Sir or Madam,',closing:'Yours faithfully,',purpose:'I am writing to complain about / enquire about / request...',paras:[['第1段 · 目的','直接说明写信原因。不要复制题目原句。'],['第2段 · Bullet 1','回答第一个任务点，并补充时间、地点或背景。'],['第3段 · Bullet 2','回答第二个任务点，解释影响或原因。'],['第4段 · Bullet 3','回答第三个任务点，明确希望对方采取什么行动。'],['最后 · 收尾','I would appreciate it if you could... / I look forward to your response.']]},
 {name:'Semi-formal 半正式信',signal:'认识对方，但有工作或礼貌距离，例如经理、老师、房东或邻居。',greeting:'Dear Mr Smith / Dear Ms Chen,',closing:'Yours sincerely, / Kind regards,',purpose:'I am writing regarding... / I am writing to ask whether...',paras:[['第1段 · 目的','说明来意，同时保持礼貌。'],['第2段 · Bullet 1','交代相关情况或问题。'],['第3段 · Bullet 2','解释原因、影响或你的安排。'],['第4段 · Bullet 3','提出具体、合理的请求或解决办法。'],['最后 · 收尾','Thank you for considering my request. / I hope you can accept my apology.']]},
 {name:'Informal 非正式信',signal:'写给朋友或家人，可以使用缩写、问候和较自然的感情表达。',greeting:'Dear Amy, / Hi Amy,',closing:'Best wishes, / Take care,',purpose:"Hope you're doing well! I'm writing to invite / thank / tell you...",paras:[['第1段 · 问候和目的','简单问候后马上说明为什么写信。'],['第2段 · Bullet 1','回答第一个任务点，可加入个人感受。'],['第3段 · Bullet 2','回答第二个任务点，语气自然。'],['第4段 · Bullet 3','回答第三个任务点并说明下一步安排。'],['最后 · 收尾',"Let me know if you can make it! / Hope to hear from you soon!"]]}
]
const essays=[
 {name:'同意 / 不同意',signal:'To what extent do you agree or disagree? / Do you agree or disagree?',position:'开头必须表态；结尾保持同一立场。',paras:[['P1 · Introduction','改写题目。I largely agree/disagree with this view because [理由1] and [理由2].'],['P2 · Reason 1','One main reason is that [观点]. This is because [解释]. For example, [例子]. Therefore, [回扣题目].'],['P3 · Reason 2','Another important reason is that [观点]. In other words, [解释]. For instance, [例子].'],['P4 · Conclusion','In conclusion, I believe that [重申立场] because [概括两个理由].']]},
 {name:'双边讨论',signal:'Discuss both views and give your own opinion.',position:'必须完整讨论双方，并明确自己的观点。',paras:[['P1 · Introduction','改写两种观点。This essay will discuss both views, although I believe that [你的立场].'],['P2 · View A','On the one hand, some people believe [观点A]. This is because [解释]. For example, [例子].'],['P3 · View B + Opinion','On the other hand, others argue [观点B]. [解释+例子]. I find this view more convincing because [原因].'],['P4 · Conclusion','In conclusion, both views have some value, but I believe [你的立场].']]},
 {name:'优点 / 缺点',signal:'What are the advantages and disadvantages? / Do the advantages outweigh the disadvantages?',position:'若有 outweigh，必须明确哪边更大；普通优缺点题不强制选边。',paras:[['P1 · Introduction','改写题目。This development has both benefits and drawbacks. [若问outweigh：Overall, I believe the advantages are greater.]'],['P2 · Advantages','One major advantage is that [优点]. This means [解释]. For example, [例子].'],['P3 · Disadvantages','However, a possible drawback is that [缺点]. This can lead to [后果]. For instance, [例子].'],['P4 · Conclusion','In conclusion, although [缺点], [优点/总体判断].']]},
 {name:'问题 / 解决',signal:'What problems does this cause? What measures can be taken? / What are the causes and solutions?',position:'仔细区分题目问 problems 还是 causes。',paras:[['P1 · Introduction','改写问题。This essay will examine the main [problems/causes] and suggest practical solutions.'],['P2 · Problem or Cause','The main [problem/cause] is [观点]. This happens because [原因], and it can result in [后果].'],['P3 · Solution','One practical solution is for [政府/学校/个人] to [行动]. If this is done, [为什么有效]. For example, [例子].'],['P4 · Conclusion','In conclusion, [问题] can be reduced if [责任方] takes [措施].']]},
 {name:'两问型',signal:'题目最后有两个不同问题，例如 Why...? What effects...? / Why...? Is this positive or negative?',position:'两个主体段各回答一个问题，不要漏答。',paras:[['P1 · Introduction','改写题目，并用一句话简答两个问题。This is mainly because [答案1], and I believe [答案2].'],['P2 · Question 1','回答第一个问题。The main reason is that [原因]. This is because [解释]. For example, [例子].'],['P3 · Question 2','回答第二个问题。I believe this has a [positive/negative] effect because [解释]. For instance, [例子].'],['P4 · Conclusion','In conclusion, [概括第一个答案], while [概括第二个答案].']]}
]
</script>
<template><section class="writing-guide"><div class="guide-head"><el-tag effect="dark">6.5 STABLE TEMPLATE</el-tag><h2>{{kind==='letter'?'G 类书信：三种语气稳定模板':'G 类大作文：五种题型稳定模板'}}</h2><p>先判断类型，再按段落完成任务。模板只负责结构，方括号内容必须根据题目替换。</p></div><el-tabs type="border-card"><el-tab-pane v-for="item in kind==='letter'?letters:essays" :key="item.name" :label="item.name"><el-alert :title="`如何识别：${item.signal}`" type="success" :closable="false" show-icon/><div v-if="kind==='letter'" class="letter-basics"><div><small>称呼</small><b>{{(item as typeof letters[number]).greeting}}</b></div><div><small>目的句</small><b>{{(item as typeof letters[number]).purpose}}</b></div><div><small>结尾</small><b>{{(item as typeof letters[number]).closing}}</b></div></div><el-alert v-else :title="`立场要求：${(item as typeof essays[number]).position}`" type="warning" :closable="false"/><div class="paragraph-plan"><div v-for="([title,content]) in item.paras" :key="title"><b>{{title}}</b><p>{{content}}</p></div></div><div class="exam-check"><b>考场检查</b><template v-if="kind==='letter'">：目的是否清楚？三个 bullet 是否全部回答？语气和称呼结尾是否一致？是否至少 150 词？</template><template v-else>：是否回答所有问题？开头是否有立场？每个主体段是否有解释和例子？结论是否与开头一致？是否至少 250 词？</template></div></el-tab-pane></el-tabs></section></template>
